/**
 * Verbatim AI — GenAI Backend API
 * ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, threads, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Thread** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a thread. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Stay tuned Watch updates and breaking changes from our [CHANGELOG](https://docs.verbatim-ai.com/docs/api-changelog). Full documentation on [our website](https://docs.verbatim-ai.com/docs/api-and-integrations)  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccessTokenItem } from './accessTokenItem';

/**
* Paginated list of the access tokens of the caller\'s organization.
*/
export class AccessTokenListResponse {
    /**
    * Zero-based index of the returned page.
    */
    'pageIndex'?: number;
    /**
    * Access tokens contained in this page, newest first, expired ones included.
    */
    'items'?: Array<AccessTokenItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pageIndex",
            "baseName": "pageIndex",
            "type": "number"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<AccessTokenItem>"
        }    ];

    static getAttributeTypeMap() {
        return AccessTokenListResponse.attributeTypeMap;
    }
}

