/**
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Payload to create a custom agent inside your organization.  Only `name` is required. Every other field falls back to a documented default, so the smallest useful body is `{\"name\": \"...\"}` — and each field left out stays tied to the platform default rather than being frozen at today\'s value.  The created agent is always a custom one: it is attached to the organization carried by your credentials, `lock` is `false` and `default` is `false`. Core agents are seeded by the platform and cannot be created over the API. 
*/
export class AgentCreateRequest {
    /**
    * Human-readable name of the agent. Max 128 characters, and unique in the listing you see — a name one of your own agents uses, or one a platform agent (`lock: true`) carries, answers `409`. Compared exactly, so `Support` and `support` are two names and `Verbatim Default v2` is free.
    */
    'name': string;
    /**
    * Free-form description of what this agent is for.
    */
    'description'?: string;
    /**
    * Chunks the vector search returns, before re-ranking narrows them down. Defaults to `5`.
    */
    'topK'?: number;
    /**
    * Whether retrieved chunks are re-ranked by an LLM before the answer is generated. Defaults to `true`.
    */
    'rerank'?: boolean;
    /**
    * Chunks kept after re-ranking. Omit to track the platform default.
    */
    'rerankTopK'?: number;
    /**
    * First third of the system instruction — what the model is looking at. Omit to track the platform default.
    */
    'context'?: string;
    /**
    * Second third of the system instruction — how the model should act. Omit to track the platform default.
    */
    'behaviour'?: string;
    /**
    * Last third of the system instruction — the tone it should take. Omit to track the platform default.
    */
    'spirit'?: string;
    /**
    * When `false`, previous posts of the session are not replayed. Defaults to `true`.
    */
    'useHistory'?: boolean;
    /**
    * Number of trailing posts replayed. Omit to replay the whole session.
    */
    'historySize'?: number;
    /**
    * Reasoning budget the model spends before answering. Defaults to `HIGH`.
    */
    'thinkingMode'?: AgentCreateRequest.ThinkingModeEnum;
    /**
    * Sampling temperature, between 0 and 1. Omit to leave the model default untouched.
    */
    'temperature'?: number;
    /**
    * Model used for re-ranking. Must be one of the names `GET /v1/config/model` advertises.
    */
    'rerankModel'?: string;
    /**
    * Model used to generate the answer. Must be one of the names `GET /v1/config/model` advertises. Omit to keep whatever model the session was created with.
    */
    'baseModel'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "topK",
            "baseName": "topK",
            "type": "number"
        },
        {
            "name": "rerank",
            "baseName": "rerank",
            "type": "boolean"
        },
        {
            "name": "rerankTopK",
            "baseName": "rerankTopK",
            "type": "number"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "string"
        },
        {
            "name": "behaviour",
            "baseName": "behaviour",
            "type": "string"
        },
        {
            "name": "spirit",
            "baseName": "spirit",
            "type": "string"
        },
        {
            "name": "useHistory",
            "baseName": "useHistory",
            "type": "boolean"
        },
        {
            "name": "historySize",
            "baseName": "historySize",
            "type": "number"
        },
        {
            "name": "thinkingMode",
            "baseName": "thinkingMode",
            "type": "AgentCreateRequest.ThinkingModeEnum"
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "number"
        },
        {
            "name": "rerankModel",
            "baseName": "rerankModel",
            "type": "string"
        },
        {
            "name": "baseModel",
            "baseName": "baseModel",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AgentCreateRequest.attributeTypeMap;
    }
}

export namespace AgentCreateRequest {
    export enum ThinkingModeEnum {
        Low = <any> 'LOW',
        High = <any> 'HIGH'
    }
}
