/**
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Chunk } from './chunk';

/**
* Paginated list of chunks. Echoes the filters that were actually applied — a filter that was dropped as empty does not appear here.
*/
export class ChunkListResponse {
    /**
    * Echo of the corpus filter, when one was applied.
    */
    'corpusId'?: string;
    /**
    * Echo of the document filter, when one was applied.
    */
    'documentId'?: string;
    /**
    * Echo of the hash filter, when one was applied.
    */
    'hash'?: string;
    /**
    * Echo of the page filter, when one was applied.
    */
    'page'?: number;
    /**
    * Echo of the metadata fragment used to filter the listing, when applicable.
    */
    'metadata'?: { [key: string]: any | null; };
    /**
    * Zero-based index of the returned page.
    */
    'pageIndex': number;
    /**
    * Number of items requested per page.
    */
    'pageSize': number;
    /**
    * Total number of chunks matching the filters across every page.
    */
    'total': number;
    /**
    * Chunks contained in this page, in reading order: by document, then by the first page each chunk covers, then by id. `body` is present only when `body=true` was passed.
    */
    'items'?: Array<Chunk>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "corpusId",
            "baseName": "corpusId",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any | null; }"
        },
        {
            "name": "pageIndex",
            "baseName": "pageIndex",
            "type": "number"
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Chunk>"
        }    ];

    static getAttributeTypeMap() {
        return ChunkListResponse.attributeTypeMap;
    }
}

