/**
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Patch a chunk. Only the fields present in the body are applied; the rest keep their current value. `id`, `documentId`, `corpusId` and `hash` are not patchable — a chunk cannot be moved to another document, and `hash` describes the text the pipeline embedded.
*/
export class ChunkUpdateRequest {
    /**
    * Replacement page span: 1-based page numbers the chunk covers. Sent empty (`[]`) it clears the span, which is what a chunk belonging to no page in particular carries. Values are sorted and de-duplicated server-side, and a value below 1 is refused.
    */
    'pages'?: Array<number>;
    /**
    * Replacement metadata. This **replaces** the object rather than merging into it — send the full map you want stored, and `{}` to clear it.
    */
    'metadata'?: { [key: string]: any | null; };
    /**
    * Replacement chunk text, written to object storage. **The vector is not recomputed**: after this call the stored embedding still describes the previous text, so the chunk keeps being retrieved for the old wording and answers with the new one. That is the intended behaviour for a typo or a redaction, and the wrong tool for a rewrite — re-ingest the document for that.
    */
    'body'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pages",
            "baseName": "pages",
            "type": "Array<number>"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any | null; }"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ChunkUpdateRequest.attributeTypeMap;
    }
}

