/**
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* One embeddable piece of a document: the text that was vectorised, where it came from, and the metadata the ingestion pipeline attached to it.
*/
export class Chunk {
    /**
    * Unique identifier of the chunk (UUIDv4). Same id the `attachment` records of a post point at.
    */
    'id': string;
    /**
    * Document the chunk was cut from.
    */
    'documentId': string;
    /**
    * Corpus owning the document. Not stored on the chunk — resolved through the document — and reported here because it is half of the storage key of `body`.
    */
    'corpusId': string;
    /**
    * 1-based page numbers the chunk spans, ascending. A chunk is built from consecutive elements and may cross page boundaries, so this is a span rather than a single page. **Empty** for a chunk that belongs to no page in particular — the document summary is the usual case.
    */
    'pages'?: Array<number>;
    /**
    * MD5 of the chunk body as it was pushed to storage. Equal hashes mean equal text, which is how duplicated content is found across documents. Read-only — it is computed by the ingestion pipeline.
    */
    'hash'?: string;
    /**
    * Arbitrary JSON metadata attached by the ingestion pipeline. `kind` is the key the platform itself sets — `chunk` for a piece of the document, `summary` for the generated summary.
    */
    'metadata'?: { [key: string]: any | null; };
    /**
    * The chunk text, read from object storage. Present on `GET /v1/chunk/{chunkId}`, and on the listings only when `body=true` was passed. An empty string means the row exists but its stored body does not — a broken chunk, which is one of the things this API exists to surface.
    */
    'body'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "corpusId",
            "baseName": "corpusId",
            "type": "string"
        },
        {
            "name": "pages",
            "baseName": "pages",
            "type": "Array<number>"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any | null; }"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Chunk.attributeTypeMap;
    }
}

