/**
 * Verbatim AI — GenAI Backend API
 * ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, threads, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Thread** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a thread. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Stay tuned Watch updates and breaking changes from our [CHANGELOG](https://verbatim-ai.gitbook.io/docs/integration/changelog)  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Body of POST /v1/doc/url. Names a web page to print to PDF and ingest into a corpus.
*/
export class DocumentUrlRequest {
    /**
    * ID of the corpus the document will be ingested into.
    */
    'corpusId': string;
    /**
    * Absolute `https` URL of an HTML page, at most 2048 characters. It may not carry credentials (`user:password@`) — send those in `headers`. Stored in the document\'s `metadata.url`.
    */
    'url': string;
    /**
    * Rendering scale of the page, from `0.1` to `2`. Below 1 fits more of the page on each PDF page. Defaults to `1`.
    */
    'scale'?: number;
    /**
    * HTTP headers sent when loading the page — typically `Authorization` or `Cookie` for a page behind a login. Sent only to the page\'s own origin (scheme, host and port of `url`), never to the third-party assets it loads; never stored. At most 20.
    */
    'headers'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "corpusId",
            "baseName": "corpusId",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "scale",
            "baseName": "scale",
            "type": "number"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return DocumentUrlRequest.attributeTypeMap;
    }
}

