/**
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Payload to patch a document. Only the fields you set are updated; omit a field to leave it unchanged.
*/
export class DocumentUpdateRequest {
    /**
    * New filename, including extension. 1–256 characters. Display only — it does not move the stored object nor re-trigger ingestion. Omit to keep the current filename.
    */
    'filename'?: string;
    /**
    * New creation date of the **source** document (ISO-8601, UTC). Describes the original file, not the platform row — `createdAt` is not affected. Omit to keep the current value.
    */
    'docCreate'?: Date;
    /**
    * New last-modified date of the **source** document (ISO-8601, UTC). Describes the original file, not the platform row — `updatedAt` is not affected. Omit to keep the current value.
    */
    'docUpdate'?: Date;
    /**
    * New JSON metadata. When provided, **replaces** the existing metadata map; omit to keep it unchanged.
    */
    'metadata'?: { [key: string]: any | null; };
    /**
    * New tag list. When provided, **replaces** the existing tags; omit to keep them unchanged. Send `[]` to clear every tag. Blanks are dropped and duplicates collapsed; at most 32 tags of 64 characters each.
    */
    'tags'?: Array<string>;
    /**
    * New chunking configuration — an Unstructured chunking option set (`strategy`, `max_characters`, `new_after_n_chars`, `overlap`, `overlap_all`, `combine_text_under_n_chars`, `multipage_sections`). See `DocumentInitRequest.chunk` for the full key reference.  When provided it **replaces** the stored object wholesale — there is no per-key merge, so resend every key you want to keep. Omit the field to leave the configuration untouched, or send `{}` to drop it and fall back to the platform default.  Applies to the **next** ingestion. Changing it does not re-chunk an already ingested document: call `PUT /v1/doc/{id}/init` and re-commit to rebuild the embeddings with the new configuration. 
    */
    'chunk'?: { [key: string]: any | null; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string"
        },
        {
            "name": "docCreate",
            "baseName": "docCreate",
            "type": "Date"
        },
        {
            "name": "docUpdate",
            "baseName": "docUpdate",
            "type": "Date"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any | null; }"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "chunk",
            "baseName": "chunk",
            "type": "{ [key: string]: any | null; }"
        }    ];

    static getAttributeTypeMap() {
        return DocumentUpdateRequest.attributeTypeMap;
    }
}

