/**
 * Verbatim AI — GenAI Backend API
 * ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, threads, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Thread** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a thread. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Stay tuned Watch updates and breaking changes from our [CHANGELOG](https://docs.verbatim-ai.com/docs/api-changelog). Full documentation on [our website](https://docs.verbatim-ai.com/docs/api-and-integrations)  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Model } from './model';

/**
* LLM models supported by the platform, everything a client needs to let someone choose one.  Not paginated — the catalog is a handful of entries and `models` always holds all of them, in the order the platform means them to be offered. `total` is their number, so a client can size a picker without walking the list.  `items` is the same list reduced to its identifiers, kept for clients written against the first version of this endpoint. It is deprecated and derived from `models`, so the two can never disagree: read `models[].id` instead. 
*/
export class ModelListResponse {
    /**
    * Number of models in `models`.
    */
    'total': number;
    /**
    * Supported models, in the order they are meant to be offered. The first is the one to preselect.
    */
    'models'?: Array<Model>;
    /**
    * **Deprecated** — identifiers of the supported models, without the display fields. Superseded by `models[].id`, which carries the same values in the same order. Still served for existing clients; it will be removed in a future release.
    *
    * @deprecated
    */
    'items'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "models",
            "baseName": "models",
            "type": "Array<Model>"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ModelListResponse.attributeTypeMap;
    }
}

