/**
 * Verbatim AI — GenAI Backend API
 * ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 5 domains: - **Corpus** — a knowledge base. Holds documents, threads, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Chunk** — one embeddable piece of a document, produced by ingestion. The unit retrieval actually returns. - **Thread** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a thread. Answers reference attachments (the chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Stay tuned Watch updates and breaking changes from our [CHANGELOG](https://verbatim-ai.gitbook.io/docs/integration/changelog)  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* One LLM the platform is configured to serve, with what a client needs to present it.  `id` is the contract: it is the value an agent\'s `baseModel` or `rerankModel` is set to, and the only field the server reads back. The other three exist to be rendered — a picker built from this endpoint shows `name`, `description` and `iconUrl` and sends `id`.  `name` and `description` are editorial and may be reworded at any time; do not match on them. Which concrete provider model an `id` runs on is deliberately absent — it changes under you without the `id` changing, which is the point of naming the alias. 
*/
export class Model {
    /**
    * Identifier of the model — the value to send anywhere a model is named.
    */
    'id': string;
    /**
    * Display name, for a model picker or the header of an answer.
    */
    'name'?: string;
    /**
    * One-line description of what the model is good for, for a tooltip or a line under the name.
    */
    'description'?: string;
    /**
    * Absolute URL of the model\'s icon — the provider\'s own logo, an SVG. Hosted off-platform, so render it as a remote image and keep a fallback for the request failing.
    */
    'iconUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "iconUrl",
            "baseName": "iconUrl",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Model.attributeTypeMap;
    }
}

