/**
 * Verbatim AI — GenAI Backend API
 *   ## Concepts API of the **Verbatim AI** Retrieval-Augmented-Generation (RAG) platform is built over 4 domains: - **Corpus** — a knowledge base. Holds documents, sessions, and is bound to an embedding model and a summary LLM. - **Document** — a file ingested into a corpus (PDF, DOCX, HTML…). - **Session** — a conversation thread bound to one or more corpora. - **Post** — a single user query or system answer inside a session. Answers reference attachments (document chunks used as context).  ## Authentication Two authentication methods are accepted on endpoints:  | Method | Header | Allowed HTTP methods | Use case | |--------|--------|----------------------|----------| | **JWT Bearer** | `Authorization: Bearer <jwt>` | All | Server-to-server calls with your RSA-signed JWT | | **Access Token** | `X-Access-Token: <token>` | **Defined by the scope of the token** | Short-lived tokens issued by `POST /v1/access-token/` |  ## API status Get a fresh status from our [API Status dashboard](https://verbatim-ai.openstatus.dev/). Events, maintenance schedules and incidents will be reported in this page.  ## Conventions - **Pagination** — list endpoints accept `pageSize` (default `25`) and `pageIndex` (default `0`). - **IDs** — all resource identifiers are UUIDv4 strings. - **Timestamps** — ISO-8601 (`2026-04-23T04:06:51Z`). - **Errors** — non-2xx responses return a JSON body matching the `Error` schema. --- 
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@verbatim-ai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WidgetPost {
    /**
    * Unique identifier of the post
    */
    'id'?: string;
    /**
    * Message text; AI answers may contain markdown and a Sources section
    */
    'text'?: string;
    /**
    * Who sent this message: USER for end-user queries, SYSTEM for AI-generated answers
    */
    'owner'?: WidgetPost.OwnerEnum;
    /**
    * ISO language code used when generating the answer
    */
    'lang'?: string;
    /**
    * Timestamp when the message was created
    */
    'sentAt'?: Date;
    /**
    * Number of source document chunks cited in this answer (0 for user messages)
    */
    'attachment'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "WidgetPost.OwnerEnum"
        },
        {
            "name": "lang",
            "baseName": "lang",
            "type": "string"
        },
        {
            "name": "sentAt",
            "baseName": "sentAt",
            "type": "Date"
        },
        {
            "name": "attachment",
            "baseName": "attachment",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return WidgetPost.attributeTypeMap;
    }
}

export namespace WidgetPost {
    export enum OwnerEnum {
        User = <any> 'USER',
        System = <any> 'SYSTEM'
    }
}
